import { UnitType } from "classes/unitType"
import { ID } from "lib/w3ts/globals/ids"



export const UNIT_TYPE = {

   Arbalist: new UnitType("n00X"), 
   AncientOfWar : new UnitType("nwnr"),
   AncientOfLife : new UnitType(ID.Unit.AncientOfLife), 
   Assassin : new UnitType("nass"), 
   Brawler : new UnitType("E001"), 
   BrawlerAlter : new UnitType("h00I"), 
   Bandit : new UnitType("n002"), 
   BanditLord : new UnitType("n005"), 
   BanditSpearman : new UnitType("n003"), 
   BattleGolem : new UnitType("narg"), 
   BloodElfArcher : new UnitType("n00C"), 
   BloodElfBreaker : new UnitType("hspt"), 
   BloodElfMage : new UnitType("hmpr"),
   Captain1 : new UnitType("hcth"), 
   Captain2 : new UnitType("h00S"), 
   Catapult : new UnitType("hmtm"),
   Commander : new UnitType("h00D"), 
   DraeneiDarkslayer : new UnitType("ndrd"), 
   DraeneiDemolisher : new UnitType("ncat"), 
   DraeneiGuardian : new UnitType("ndrf"), 
   DraeneiSeer : new UnitType("ndrs"), 
   DraeneiVindicator : new UnitType("n00I"), 
   DragonHawk : new UnitType("nws1"), 
   DragonTurtle : new UnitType("nhyc"), 
   DruidOfTheClaw : new UnitType("edoc"), 
   Dryad : new UnitType("edry"), 
   DwarfAxethrower : new UnitType("n006"), 
   DwarfClansman : new UnitType("e00E"), 
   DwarfElite : new UnitType("e00F"), 
   Enforcer : new UnitType("n008"), 
   EredarWarlock : new UnitType("nerw"), 
   FelOrcWarlock : new UnitType("nchw"), 
   Footman1 : new UnitType("hfoo"), 
   Footman2 : new UnitType("h017"), 
   Ghoul : new UnitType("ugho"), 
   GiantSkeleton : new UnitType("nfgl"), 
   Grunt : new UnitType("o002"), 
   GryphonRider : new UnitType("hgry"), 
   Gyrocopter : new UnitType("hgyr"), 
   InfernalContraption : new UnitType("ninc"), 
   InfernalJuggernaut : new UnitType("nina"), 
   InfernalMachine : new UnitType("ninm"), 
   HighElfApprenticeSwordsman : new UnitType("h00T"), 
   HighElfArcher : new UnitType("nhea"), 
   HighElfGuardian : new UnitType("h010"), 
   HighElfHealer : new UnitType("nemi"), 
   HighElfKnight : new UnitType("h005"), 
   HighElfSwordsman : new UnitType("hhes"), 
   HippogryphRider : new UnitType("ehpr"), 
   HumanBattleship : new UnitType("hbsh"), 
   HumanFrigate : new UnitType("hdes"), 
   IronCaptain : new UnitType("h01P"), 
   IronGuard : new UnitType("h01O"), 
   IronMagi : new UnitType("h01E"), 
   IronMortarTeam : new UnitType("h001"), 
   IronRifleman : new UnitType("h008"), 
   Knight : new UnitType("h00L"),
   Lich : new UnitType(ID.Unit.LichCustom),
   MagiDefender : new UnitType("h00K"), 
   ManaAddict : new UnitType("H00R"), 
   ManaAddictAlter : new UnitType("h00B"), 
   Militia1 : new UnitType("h007"), 
   Militia2 : new UnitType("h015"), 
   MountainGiant : new UnitType("e005"), 
   MurlocCliffRunner : new UnitType("nmcf"), 
   MurlocReaver : new UnitType("nnmg"), 
   MurlocSnareCaster : new UnitType("nmsn"), 
   MurlocTideWarrior : new UnitType("nmtw"),
   NavyCaptain : new UnitType(ID.Unit.NavyCaptain),
   NavyFootman : new UnitType(ID.Unit.NavyFootman),
   NavyMarine : new UnitType(ID.Unit.NavyMarine),
   NagaMyrmidon : new UnitType("nmyr"), 
   NagaSiren : new UnitType("nnsw"), 
   NagaRoyalGuard : new UnitType("nnrg"), 
   Necromancer : new UnitType("unec"), 
   NightElfBattleship : new UnitType("ebsh"), 
   NightElfFrigate : new UnitType("edes"), 
   NightElfRanger : new UnitType("earc"), 
   NightElfEliteRanger : new UnitType("e000"), 
   NightElfSentry : new UnitType("nwat"), 
   Ogre : new UnitType("nogo"), 
   OrcWarchief : new UnitType("owad"), 
   Rogue : new UnitType("n00L"), 
   SeigeEngine : new UnitType("h011"), 
   SeigeEngineDamaged : new UnitType("hmtt"), 
   SeigeGolem : new UnitType("nsgg"), 
   ShiftMaster : new UnitType("E002"), 
   ShiftMasterAlter : new UnitType("h00Q"), 
   SkeletonArcher : new UnitType("nsca"), 
   SkeletonWarrior : new UnitType("nske"), 
   SkeletonMage : new UnitType("uskm"), 
   SnapDragon : new UnitType("nsnp"), 
   Sorceress : new UnitType("h00C"), 
   Summoner : new UnitType("n018"), 
   SupremeWizard : new UnitType("n00A"), 
   StormSummoner : new UnitType("nchp"), 
   Tactician : new UnitType("H009"), 
   TacticianAlter : new UnitType("h00Y"), 
   TimeMage : new UnitType("H00J"), 
   TimeMageAlter : new UnitType("h00Z"), 
   TrollAxethrower : new UnitType("nftr"), 
   WarGolem : new UnitType("nwrg"), 
   Warlock : new UnitType("nw2w"), 
   WaterElemental1 : new UnitType("hwat"), 
   WaterElemental2 : new UnitType("hwt2"), 
   WaterElemental3 : new UnitType("hwt3"),
   NightElfWarden : new UnitType(ID.Unit.Nightelfassassin),
   VillagerMale1 : new UnitType(ID.Unit.Villagerman),
   VillagerMale2 : new UnitType(ID.Unit.Villagerman2),
   VillagerFemale1 : new UnitType(ID.Unit.Villagerwoman),
   VillagerChild1 : new UnitType(ID.Unit.Villagerkid),
   VillagerChild2 : new UnitType(ID.Unit.Villagerkid2),
   
   // Aspects
   AspectOfTheTides : new UnitType(ID.Unit.AspectOfTheTides),
   AspectOfTheStorm: new UnitType(ID.Unit.AspectOfTheStorm),
   AspectOfTheEarth : new UnitType(ID.Unit.AspectOfTheEarth),
   AspectOfTheForest : new UnitType(ID.Unit.AspectOfTheForest),
   AspectOfDeath: new UnitType(ID.Unit.AspectOfDeath),

   // Buildings
   CastleGateOpen : new UnitType(ID.Unit.CastleGateOpen), 
   CastleGateClosed : new UnitType(ID.Unit.CastleGateClosed),
   CityBuilding03 : new UnitType(ID.Unit.CitybuildingSmall3), 
   CityBuilding04 : new UnitType(ID.Unit.CitybuildingSmall4),
   CityBuilding05 : new UnitType(ID.Unit.CitybuildingSmall5),
   CityBuilding09 : new UnitType(ID.Unit.CitybuildingSmall9),
   CityBuilding10 : new UnitType(ID.Unit.CitybuildingSmalla),
   CityBuilding11 : new UnitType(ID.Unit.CitybuildingSmallb),
   CityBuilding15 : new UnitType(ID.Unit.CityBuildingLarge3),
   DwarvenGateClosed : new UnitType(ID.Unit.DwarvenGateClosed), 
   DwarvenGateOpen : new UnitType(ID.Unit.DwarvenGateOpen), 
   MercTent : new UnitType(ID.Unit.MercTent),
   MercLookout : new UnitType(ID.Unit.MercLookout),
   Nerubianziggurat : new UnitType(ID.Unit.Nerubianziggurat), 
   WildhammerCottage : new UnitType("h01W"), 
   WildhammerFarmLarge : new UnitType("h01F"), 
   WildhammerFarm : new UnitType("h01U"), 
   WildhammerMound : new UnitType("h01X")
    
}
