import { Rectangle } from './rect'


export class Rectangles {
	/// / AUTO DEFINE
	static Left_Start: Rectangle
	static Left_Hero: Rectangle
	static Camp_Top: Rectangle
	static Left_Tree: Rectangle
	static Left_Workshop: Rectangle
	static Left_Arcane: Rectangle
	static Right_Hero: Rectangle
	static Right_Start: Rectangle
	static Right_Tree: Rectangle
	static Right_Arcane: Rectangle
	static Right_Workshop: Rectangle
	static Camp_Bottom: Rectangle
	static Left_Orc: Rectangle
	static Right_Orc: Rectangle
	static Furbolg_Left: Rectangle
	static Furbolg_Right: Rectangle
	static Left_Start_Bottom: Rectangle
	static Left_Start_Top: Rectangle
	static Right_Start_Top: Rectangle
	static Big_Bottom_Left: Rectangle
	static Big_Middle_Left: Rectangle
	static Big_Top_Left: Rectangle
	static Left_Castle: Rectangle
	static Left_City: Rectangle
	static Right_City: Rectangle
	static Right_Castle: Rectangle
	static Left_High_Elves: Rectangle
	static Left_Shipyard: Rectangle
	static Right_Shipyard: Rectangle
	static Right_Start_Bottom: Rectangle
	static Right_High_Elves: Rectangle
	static Naga_Right: Rectangle
	static Naga_Left: Rectangle
	static Murloc_Left: Rectangle
	static Murloc_Right: Rectangle
	static Left_Elemental_Start: Rectangle
	static Front_Town_Left: Rectangle
	static City_Elves_Left: Rectangle
	static Blacksmith_Left: Rectangle
	static Front_City_Right: Rectangle
	static City_Elves_Right: Rectangle
	static Blacksmith_Right: Rectangle
	static Arcane_Hero_Right: Rectangle
	static Arcane_Hero_Left: Rectangle
	static Murloc_Gate_Left: Rectangle
	static Murloc_Gate_Right: Rectangle
	static Big_Top_Right: Rectangle
	static Big_Middle_Right: Rectangle
	static Big_Bottom_Right: Rectangle
	static Big_Bottom_Left_Center: Rectangle
	static Big_Bottom_Right_Center: Rectangle
	static Big_Top_Right_Center: Rectangle
	static Big_Top_Left_Center: Rectangle
	static Big_Middle_Right_Center: Rectangle
	static Aspect_of_Forest_Left: Rectangle
	static Aspect_of_Forest_Left_Gate: Rectangle
	static Aspect_of_Forest_Right_Gate: Rectangle
	static Arcane_Left_Top: Rectangle
	static Arcane_Left_Bottom: Rectangle
	static Arcane_Right_Top: Rectangle
	static Arcane_Right_Bottom: Rectangle
	static Zombie_End_Left: Rectangle
	static Zombie_End_Right: Rectangle
	static Death_Gate_Left: Rectangle
	static Death_Gate_Right: Rectangle
	static Elf_Base_Right: Rectangle
	static Elf_Base_Left: Rectangle
	static Undead_Right: Rectangle
	static Undead_Left: Rectangle
	static Human_Shipyard_Left: Rectangle
	static Human_Shipyard_Right: Rectangle
	static Right_Everything: Rectangle
	static Left_Everything: Rectangle
	static Left_Mage_Base: Rectangle
	static Right_Mage_Base: Rectangle
	static Murloc_Spawn_Left: Rectangle
	static Murloc_Spawn_Right: Rectangle
	static Right_Start_Middle: Rectangle
	static Aspect_of_Forest_Left_Mid: Rectangle
	static Aspect_of_Forest_Right_Mid: Rectangle
	static Aspect_of_Forest_Right: Rectangle
	static Right_Elemental_Start: Rectangle
	static Left_Start_Middle: Rectangle
	static Big_Middle_Left_Center: Rectangle
	static Night_Elf_Left: Rectangle
	static Night_Elf_Right: Rectangle
	static Rock_Left: Rectangle
	static Rock_Right: Rectangle
	static Rock_Gate_Right: Rectangle
	static Rock_Gate_Left: Rectangle
	static EventTL1: Rectangle
	static EventTL2: Rectangle
	static EventTL3: Rectangle
	static EventBL1: Rectangle
	static EventBL2: Rectangle
	static EventBL3: Rectangle
	static EventBR1: Rectangle
	static EventBR2: Rectangle
	static EventBR3: Rectangle
	static EventTR1: Rectangle
	static EventTR2: Rectangle
	static EventTR3: Rectangle
	static EventCenter: Rectangle

	static defineGlobals (): void {
		Rectangles.Left_Start = Rectangle.fromHandle(gg_rct_Left_Start)
		Rectangles.Left_Hero = Rectangle.fromHandle(gg_rct_Left_Hero)
		Rectangles.Camp_Top = Rectangle.fromHandle(gg_rct_Camp_Top)
		Rectangles.Left_Tree = Rectangle.fromHandle(gg_rct_Left_Tree)
		Rectangles.Left_Workshop = Rectangle.fromHandle(gg_rct_Left_Workshop)
		Rectangles.Left_Arcane = Rectangle.fromHandle(gg_rct_Left_Arcane)
		Rectangles.Right_Hero = Rectangle.fromHandle(gg_rct_Right_Hero)
		Rectangles.Right_Start = Rectangle.fromHandle(gg_rct_Right_Start)
		Rectangles.Right_Tree = Rectangle.fromHandle(gg_rct_Right_Tree)
		Rectangles.Right_Arcane = Rectangle.fromHandle(gg_rct_Right_Arcane)
		Rectangles.Right_Workshop = Rectangle.fromHandle(gg_rct_Right_Workshop)
		Rectangles.Camp_Bottom = Rectangle.fromHandle(gg_rct_Camp_Bottom)
		Rectangles.Left_Orc = Rectangle.fromHandle(gg_rct_Left_Orc)
		Rectangles.Right_Orc = Rectangle.fromHandle(gg_rct_Right_Orc)
		Rectangles.Furbolg_Left = Rectangle.fromHandle(gg_rct_Furbolg_Left)
		Rectangles.Furbolg_Right = Rectangle.fromHandle(gg_rct_Furbolg_Right)
		Rectangles.Left_Start_Bottom = Rectangle.fromHandle(gg_rct_Left_Start_Bottom)
		Rectangles.Left_Start_Top = Rectangle.fromHandle(gg_rct_Left_Start_Top)
		Rectangles.Right_Start_Top = Rectangle.fromHandle(gg_rct_Right_Start_Top)
		Rectangles.Big_Bottom_Left = Rectangle.fromHandle(gg_rct_Big_Bottom_Left)
		Rectangles.Big_Middle_Left = Rectangle.fromHandle(gg_rct_Big_Middle_Left)
		Rectangles.Big_Top_Left = Rectangle.fromHandle(gg_rct_Big_Top_Left)
		Rectangles.Left_Castle = Rectangle.fromHandle(gg_rct_Left_Castle)
		Rectangles.Left_City = Rectangle.fromHandle(gg_rct_Left_City)
		Rectangles.Right_City = Rectangle.fromHandle(gg_rct_Right_City)
		Rectangles.Right_Castle = Rectangle.fromHandle(gg_rct_Right_Castle)
		Rectangles.Left_High_Elves = Rectangle.fromHandle(gg_rct_Left_High_Elves)
		Rectangles.Left_Shipyard = Rectangle.fromHandle(gg_rct_Left_Shipyard)
		Rectangles.Right_Shipyard = Rectangle.fromHandle(gg_rct_Right_Shipyard)
		Rectangles.Right_Start_Bottom = Rectangle.fromHandle(gg_rct_Right_Start_Bottom)
		Rectangles.Right_High_Elves = Rectangle.fromHandle(gg_rct_Right_High_Elves)
		Rectangles.Naga_Right = Rectangle.fromHandle(gg_rct_Naga_Right)
		Rectangles.Naga_Left = Rectangle.fromHandle(gg_rct_Naga_Left)
		Rectangles.Murloc_Left = Rectangle.fromHandle(gg_rct_Murloc_Left)
		Rectangles.Murloc_Right = Rectangle.fromHandle(gg_rct_Murloc_Right)
		Rectangles.Left_Elemental_Start = Rectangle.fromHandle(gg_rct_Left_Elemental_Start)
		Rectangles.Front_Town_Left = Rectangle.fromHandle(gg_rct_Front_Town_Left)
		Rectangles.City_Elves_Left = Rectangle.fromHandle(gg_rct_City_Elves_Left)
		Rectangles.Blacksmith_Left = Rectangle.fromHandle(gg_rct_Blacksmith_Left)
		Rectangles.Front_City_Right = Rectangle.fromHandle(gg_rct_Front_City_Right)
		Rectangles.City_Elves_Right = Rectangle.fromHandle(gg_rct_City_Elves_Right)
		Rectangles.Blacksmith_Right = Rectangle.fromHandle(gg_rct_Blacksmith_Right)
		Rectangles.Arcane_Hero_Right = Rectangle.fromHandle(gg_rct_Arcane_Hero_Right)
		Rectangles.Arcane_Hero_Left = Rectangle.fromHandle(gg_rct_Arcane_Hero_Left)
		Rectangles.Murloc_Gate_Left = Rectangle.fromHandle(gg_rct_Murloc_Gate_Left)
		Rectangles.Murloc_Gate_Right = Rectangle.fromHandle(gg_rct_Murloc_Gate_Right)
		Rectangles.Big_Top_Right = Rectangle.fromHandle(gg_rct_Big_Top_Right)
		Rectangles.Big_Middle_Right = Rectangle.fromHandle(gg_rct_Big_Middle_Right)
		Rectangles.Big_Bottom_Right = Rectangle.fromHandle(gg_rct_Big_Bottom_Right)
		Rectangles.Big_Bottom_Left_Center = Rectangle.fromHandle(gg_rct_Big_Bottom_Left_Center)
		Rectangles.Big_Bottom_Right_Center = Rectangle.fromHandle(gg_rct_Big_Bottom_Right_Center)
		Rectangles.Big_Top_Right_Center = Rectangle.fromHandle(gg_rct_Big_Top_Right_Center)
		Rectangles.Big_Top_Left_Center = Rectangle.fromHandle(gg_rct_Big_Top_Left_Center)
		Rectangles.Big_Middle_Right_Center = Rectangle.fromHandle(gg_rct_Big_Middle_Right_Center)
		Rectangles.Aspect_of_Forest_Left = Rectangle.fromHandle(gg_rct_Aspect_of_Forest_Left)
		Rectangles.Aspect_of_Forest_Left_Gate = Rectangle.fromHandle(gg_rct_Aspect_of_Forest_Left_Gate)
		Rectangles.Aspect_of_Forest_Right_Gate = Rectangle.fromHandle(gg_rct_Aspect_of_Forest_Right_Gate)
		Rectangles.Arcane_Left_Top = Rectangle.fromHandle(gg_rct_Arcane_Left_Top)
		Rectangles.Arcane_Left_Bottom = Rectangle.fromHandle(gg_rct_Arcane_Left_Bottom)
		Rectangles.Arcane_Right_Top = Rectangle.fromHandle(gg_rct_Arcane_Right_Top)
		Rectangles.Arcane_Right_Bottom = Rectangle.fromHandle(gg_rct_Arcane_Right_Bottom)
		Rectangles.Zombie_End_Left = Rectangle.fromHandle(gg_rct_Zombie_End_Left)
		Rectangles.Zombie_End_Right = Rectangle.fromHandle(gg_rct_Zombie_End_Right)
		Rectangles.Death_Gate_Left = Rectangle.fromHandle(gg_rct_Death_Gate_Left)
		Rectangles.Death_Gate_Right = Rectangle.fromHandle(gg_rct_Death_Gate_Right)
		Rectangles.Elf_Base_Right = Rectangle.fromHandle(gg_rct_Elf_Base_Right)
		Rectangles.Elf_Base_Left = Rectangle.fromHandle(gg_rct_Elf_Base_Left)
		Rectangles.Undead_Right = Rectangle.fromHandle(gg_rct_Undead_Right)
		Rectangles.Undead_Left = Rectangle.fromHandle(gg_rct_Undead_Left)
		Rectangles.Human_Shipyard_Left = Rectangle.fromHandle(gg_rct_Human_Shipyard_Left)
		Rectangles.Human_Shipyard_Right = Rectangle.fromHandle(gg_rct_Human_Shipyard_Right)
		Rectangles.Right_Everything = Rectangle.fromHandle(gg_rct_Right_Everything)
		Rectangles.Left_Everything = Rectangle.fromHandle(gg_rct_Left_Everything)
		Rectangles.Left_Mage_Base = Rectangle.fromHandle(gg_rct_Left_Mage_Base)
		Rectangles.Right_Mage_Base = Rectangle.fromHandle(gg_rct_Right_Mage_Base)
		Rectangles.Murloc_Spawn_Left = Rectangle.fromHandle(gg_rct_Murloc_Spawn_Left)
		Rectangles.Murloc_Spawn_Right = Rectangle.fromHandle(gg_rct_Murloc_Spawn_Right)
		Rectangles.Right_Start_Middle = Rectangle.fromHandle(gg_rct_Right_Start_Middle)
		Rectangles.Aspect_of_Forest_Left_Mid = Rectangle.fromHandle(gg_rct_Aspect_of_Forest_Left_Mid)
		Rectangles.Aspect_of_Forest_Right_Mid = Rectangle.fromHandle(gg_rct_Aspect_of_Forest_Right_Mid)
		Rectangles.Aspect_of_Forest_Right = Rectangle.fromHandle(gg_rct_Aspect_of_Forest_Right)
		Rectangles.Right_Elemental_Start = Rectangle.fromHandle(gg_rct_Right_Elemental_Start)
		Rectangles.Left_Start_Middle = Rectangle.fromHandle(gg_rct_Left_Start_Middle)
		Rectangles.Big_Middle_Left_Center = Rectangle.fromHandle(gg_rct_Big_Middle_Left_Center)
		Rectangles.Night_Elf_Left = Rectangle.fromHandle(gg_rct_Night_Elf_Left)
		Rectangles.Night_Elf_Right = Rectangle.fromHandle(gg_rct_Night_Elf_Right)
		Rectangles.Rock_Left = Rectangle.fromHandle(gg_rct_Rock_Left)
		Rectangles.Rock_Right = Rectangle.fromHandle(gg_rct_Rock_Right)
		Rectangles.Rock_Gate_Right = Rectangle.fromHandle(gg_rct_Rock_Gate_Right)
		Rectangles.Rock_Gate_Left = Rectangle.fromHandle(gg_rct_Rock_Gate_Left)
		Rectangles.EventTL1 = Rectangle.fromHandle(gg_rct_EventTL1)
		Rectangles.EventTL2 = Rectangle.fromHandle(gg_rct_EventTL2)
		Rectangles.EventTL3 = Rectangle.fromHandle(gg_rct_EventTL3)
		Rectangles.EventBL1 = Rectangle.fromHandle(gg_rct_EventBL1)
		Rectangles.EventBL2 = Rectangle.fromHandle(gg_rct_EventBL2)
		Rectangles.EventBL3 = Rectangle.fromHandle(gg_rct_EventBL3)
		Rectangles.EventBR1 = Rectangle.fromHandle(gg_rct_EventBR1)
		Rectangles.EventBR2 = Rectangle.fromHandle(gg_rct_EventBR2)
		Rectangles.EventBR3 = Rectangle.fromHandle(gg_rct_EventBR3)
		Rectangles.EventTR1 = Rectangle.fromHandle(gg_rct_EventTR1)
		Rectangles.EventTR2 = Rectangle.fromHandle(gg_rct_EventTR2)
		Rectangles.EventTR3 = Rectangle.fromHandle(gg_rct_EventTR3)
		Rectangles.EventCenter = Rectangle.fromHandle(gg_rct_EventCenter)
	}
}
